export const FETCH_USER = "FETCH_USER";

export const OPEN_MODAL = "OPEN_MODAL";

export const CLOSE_MODAL = "CLOSE_MODAL";

export const FETCH_PROJECTS = "FETCH_PROJECTS";

export const FETCH_PROJECT = "FETCH_PROJECT";

export const CREATE_PROJECT = "CREATE_PROJECT";

export const FETCH_SAVES = "FETCH_SAVES";

export const FETCH_SAVE = "FETCH_SAVE";

export const FORM_ERROR = "FORM_ERROR";

export const FETCH_DRAFT = "FETCH_DRAFT";

export const FETCH_REVISION = "FETCH_REVISION";

export const CREATE_DRAFT = 'CREATE_DRAFT';

export const SET_DRAFTS = "SET_DRAFTS";

export const SET_ALL_CONFLICTS = "GET_ALL_CONFLICTS";

export const UPDATE_CONFLICT_SELECTION = "UPDATE_CONFLICT_SELECTION";
